/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bf43e8cf-2a9d-410b-ab6b-3da084908fa7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PeArLdUvT",
    "aws_user_pools_web_client_id": "ddqu1j2l9pncmu0hfrousesn5",
    "oauth": {}
};


export default awsmobile;
